### PR TITLE
Added feature to fail the build based on quality gate status

### PR DESCRIPTION
**Pull request by tasadar2**

### CODE REVIEW

**Comment by BennyBread** [comment]
We also like to have that feature back as it was in 3.0 version of the plugin. The changes make sense to me on first sight (without any deeper knowledge of the whole codebase). 
Is there a chance that this pull request gets merged to TFS 2017?

**Comment by pierre-guillot-sonarsource** [comment]
Thanks for submitting this PR. As there is no traction on this for a long time, i'm closing it. If this is still a feature valuable for you, please consider posting in our [community forum](https://community.sonarsource.com/c/suggestions/features) a feature request.

**Comment by tasadar2** [comment]
Since the build failure seems unrelated to the change, I'm curious, as a non-maintainer, was there something I should have done to retrigger the build?

**Comment by pierre-guillot-sonarsource** [comment]
To re-trigger the build you can ask a maintainer, or push a new commit, or force-push an existing commit

**Pull request closed without merging**
