### PR TITLE
fix(BUILD-1378): sonarqube-team ownership

### PR DESCRIPTION
**Pull request by julien-carsique-sonarsource**

### CODE REVIEW

**Comment by mickael-caro-sonarsource** [comment]
Hi @julien-carsique-sonarsource , i don't think sonarqube team owns this repo :)

**Comment by pierre-guillot-sonarsource** [comment]
> Hi @julien-carsique-sonarsource , i don't think sonarqube team owns this repo :)

Hey @mickael-caro-sonarsource , who should we assign as the owner?

**Comment by mickael-caro-sonarsource** [comment]
@pierre-guillot-sonarsource put me and maybe sonarcloud-team (as @gregaubert  knows a bit of this beast as well)

**Comment by pierre-guillot-sonarsource** [comment]
Closing in favor of https://github.com/SonarSource/sonar-scanner-vsts/pull/189

**Pull request closed without merging**
