### PR TITLE
VSTS-295 Bump SonarScanner for .NET and ScannerCLi versions

### PR DESCRIPTION
**Pull request by jacek-poreda-sonarsource**

### CODE REVIEW

**Comment by jacek-poreda-sonarsource** [comment]
@mickael-caro-sonarsource WIll you have time to help me with those failures?

**Comment by mickael-caro-sonarsource** [comment]
Hello @jacek-poreda-sonarsource there are some issues on the marketplace right now (well, I had already this issue 10 days ago, so I bet this is not resolved yet). I'll try to ping again VS team and check. Thanks!

**Comment by mickael-caro-sonarsource** [comment]
@jacek-poreda-sonarsource PR is green again, i'm letting it opened for now, i will set me a reminder for next week to merge and deploy.

**Comment by jacek-poreda-sonarsource** [comment]
Thanks a lot!

**Review by mickael-caro-sonarsource — APPROVED** [review]

**Pull request merged**
