### PR TITLE
VSTS-230 Download and cache Scanner for .NET at runtime

### PR DESCRIPTION
**Pull request by mickael-caro-sonarsource**
Please review our [contribution guidelines](https://github.com/SonarSource/sonar-scanner-vsts/blob/master/contributing.md).

And please ensure your pull request adheres to the following guidelines: 

- [ ] Please explain your motives to contribute this change: what problem you are trying to fix, what improvement you are trying to make
- [ ] Use the following formatting style: [SonarSource/sonar-developer-toolset](https://github.com/SonarSource/sonar-developer-toolset#code-style)
- [ ] Provide a unit test for any code you changed
- [ ] If there is a [JIRA](https://jira.sonarsource.com/browse/VSTS) ticket available, please make your commits and pull request start with the ticket ID (VSTS-XXXX)

### CODE REVIEW

**Comment by 304NotModified** [comment]
This is fixed by https://github.com/SonarSource/sonar-scanner-vsts/pull/164?

**Comment by mickael-caro-sonarsource** [comment]
Hi @304NotModified no this is a different feature (i'll change the ticket number)

**Comment by 304NotModified** [comment]
Guess this could be closed? (it's in my mentioned list - https://github.com/pulls/mentioned)

**Comment by 7PH** [comment]
As discussed with @mickael-caro-sonarsource , closing this PR as there are too many conflicts with new code. This PR's diff can still be used in the future to implement this feature in the future.

**Pull request closed without merging**
