### PR TITLE
VSTS-382 Deprecate SC v1 and SQ v5 tasks

### PR DESCRIPTION
**Pull request by lucas-paulger-sonarsource**
Please review our [contribution guidelines](https://github.com/SonarSource/sonar-scanner-vsts/blob/master/docs/contributing.md).

And please ensure your pull request adheres to the following guidelines: 

- [ ] Please explain your motives to contribute this change: what problem you are trying to fix, what improvement you are trying to make
- [ ] Use the following formatting style: [SonarSource/sonar-developer-toolset](https://github.com/SonarSource/sonar-developer-toolset#code-style)
- [ ] Provide a unit test for any code you changed
- [x] If there is a [JIRA](https://jira.sonarsource.com/browse/VSTS) ticket available, please make your commits and pull request start with the ticket ID (VSTS-XXXX)

### CODE REVIEW

**Comment by lucas-paulger-sonarsource** [comment]
SonarCloud V1 tasks show warning:
Screenshot 2024-06-06 at 22 27 17
Screenshot 2024-06-06 at 22 27 27
Screenshot 2024-06-06 at 22 27 33

SonarQube V5 show a warning
Screenshot 2024-06-06 at 22 27 48
Screenshot 2024-06-06 at 22 29 31
Screenshot 2024-06-06 at 22 29 36

**Review by 7PH — COMMENTED** [review]
FV made on SQ V5, V6 and SC V1, V2 ✅ 

I think we could also change the `task.json`:
- Use `"deprecated": true` to mark tasks as deprecated in the pipeline edit UI directly
- Maybe also use `deprecationMessage` to put a deprecation warning in the UI?

WDYT? here's the link to [the json schema for `task.json`](https://github.com/Microsoft/azure-pipelines-task-lib/blob/master/tasks.schema.json#L38)

**Comment by lucas-paulger-sonarsource** [comment]
> FV made on SQ V5, V6 and SC V1, V2 ✅
> 
> I think we could also change the `task.json`:
> 
> * Use `"deprecated": true` to mark tasks as deprecated in the pipeline edit UI directly
> * Maybe also use `deprecationMessage` to put a deprecation warning in the UI?
> 
> WDYT? here's the link to [the json schema for `task.json`](https://github.com/Microsoft/azure-pipelines-task-lib/blob/master/tasks.schema.json#L38)

Regarding
> Maybe also use `deprecationMessage` to put a deprecation warning in the UI?
I'm not quite sure what to put other than what we have in the existing warning. 

the field description is : "A tailored deprecation message containing detailed information about the task deprecation (besides the removal date and the URL leading to the task documentation) in addition to the common deprecation message."

**Review by 7PH — APPROVED** [review]
FV ok + LGTM ✅

**Pull request merged**
