### PR TITLE
Point to link on Azure DevOps Labs

### PR DESCRIPTION
**Pull request by vinijmoura**
Point to link on Azure DevOps Labs

Please review our [contribution guidelines](https://github.com/SonarSource/sonar-scanner-vsts/blob/master/contributing.md).

And please ensure your pull request adheres to the following guidelines: 

- [ ] Please explain your motives to contribute this change: what problem you are trying to fix, what improvement you are trying to make
- [ ] Use the following formatting style: [SonarSource/sonar-developer-toolset](https://github.com/SonarSource/sonar-developer-toolset#code-style)
- [ ] Provide a unit test for any code you changed
- [ ] If there is a [JIRA](https://jira.sonarsource.com/browse/VSTS) ticket available, please make your commits and pull request start with the ticket ID (VSTS-XXXX)

### CODE REVIEW

**Comment by n-b-sonar** [comment]
@vinijmoura : per contributions guidelines, could you please clarify the following
> Please explain your motives to contribute this change: what problem you are trying to fix, what improvement you are trying to make

Other than the difference of hosting website, it's not clear to me the value of sending to that other site (the `aka.ms` shortlink was precisely done in collaboration with Microsoft)

**Comment by vinijmoura** [comment]
https://docs.microsoft.com/en-us/labs/devops/sonarcloudlab/index is a old link. Refers to Visual Studio Team Services. If point to Azure DevOps Labs, we have a practical guidance. :)

**Comment by n-b-sonar** [comment]
Good point, I didn't immediately noticed that `Visual Studio Team Services` was specifically referred too.

I feel what would make most sense is to actually have https://aka.ms/sonarcloudlab shortlink updated, so that it redirects to latest (Azure DevOps) resource. Makes sense? this is something we could double-check with Microsoft.

**Comment by vinijmoura** [comment]
I prefer use the link that shows me a practical example.  Anyway MS will have to change product name.
From: Visual Studio Team Service to Azure DevOps :)

**Pull request merged**
