### PR TITLE
Change to Node10 execution handler + bumped AzPipeline Task Lib versi…

### PR DESCRIPTION
**Pull request by mickael-caro-sonarsource**
…on + required dependency bumps

Please review our [contribution guidelines](https://github.com/SonarSource/sonar-scanner-vsts/blob/master/contributing.md).

And please ensure your pull request adheres to the following guidelines: 

- [ ] Please explain your motives to contribute this change: what problem you are trying to fix, what improvement you are trying to make
- [ ] Use the following formatting style: [SonarSource/sonar-developer-toolset](https://github.com/SonarSource/sonar-developer-toolset#code-style)
- [ ] Provide a unit test for any code you changed
- [ ] If there is a [JIRA](https://jira.sonarsource.com/browse/VSTS) ticket available, please make your commits and pull request start with the ticket ID (VSTS-XXXX)

### CODE REVIEW

**Comment by ladeak** [comment]
This change is breaking our build jobs on VSTS. We get an error 

```
2021-10-04T06:15:52.0619928Z ==============================================================================
2021-10-04T06:15:52.0619928Z Task         : Prepare Analysis Configuration
2021-10-04T06:15:52.0619928Z Description  : Prepare SonarQube analysis configuration
2021-10-04T06:15:52.0619928Z Version      : 4.23.0
2021-10-04T06:15:52.0619928Z Author       : sonarsource
2021-10-04T06:15:52.0619928Z Help         : Version: 4.23.0. [More Information](http://redirect.sonarsource.com/doc/install-configure-scanner-tfs-ts.html)
2021-10-04T06:15:52.0619928Z ==============================================================================
2021-10-04T06:15:52.1244339Z ##[error]A supported task execution handler was not found. This error usually means the task does not carry an implementation that is compatible with your current operating system. Contact the task author for more details.
2021-10-04T06:15:52.1244339Z ##[debug]System.Exception: A supported task execution handler was not found. This error usually means the task does not carry an implementation that is compatible with your current operating system. Contact the task author for more details.
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.<RunAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.<RunStepAsync>d__1.MoveNext()
2021-10-04T06:15:52.1244339Z ##[section]Finishing: Prepare analysis on SonarQube
```

**Comment by mickael-caro-sonarsource** [comment]
Hi @ladeak please check that your build agent is running in version 2.144.0 minimum.

**Comment by ladeak** [comment]
Thanks for the hint, it is running 2.122.1,  I am not sure if VSTS 2017 with update 3 support a higher version than that though.

**Comment by ladeak** [comment]
We will try updating the agent version, thank you for the help.

**Comment by mmonteroq** [comment]
I'm getting the same issue, what do I need to update on the build agent?
Thanks

**Comment by ladeak** [comment]
Grab the release from here: https://github.com/Microsoft/azure-pipelines-agent and update agents.

Here is the general docs: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops

**Pull request merged**
