### PR TITLE
Bump SC extension version

### PR DESCRIPTION
**Pull request by antonio-garcia-sonarsource**
Please review our [contribution guidelines](https://github.com/SonarSource/sonar-scanner-vsts/blob/master/docs/contributing.md).

And please ensure your pull request adheres to the following guidelines: 

- [ ] Please explain your motives to contribute this change: what problem you are trying to fix, what improvement you are trying to make
- [ ] Use the following formatting style: [SonarSource/sonar-developer-toolset](https://github.com/SonarSource/sonar-developer-toolset#code-style)
- [ ] Provide a unit test for any code you changed
- [ ] If there is a [JIRA](https://jira.sonarsource.com/browse/VSTS) ticket available, please make your commits and pull request start with the ticket ID (VSTS-XXXX)

### CODE REVIEW

**Comment by antonio-garcia-sonarsource** [comment]
@mickael-caro-sonarsource I am not sure if this is all that's needed to publish the extension changes, I am hoping you could let me know if I'm missing something 🙏

**Comment by mickael-caro-sonarsource** [comment]
@antonio-garcia-sonarsource the release process is documented here : https://xtranet-sonarsource.atlassian.net/wiki/spaces/SSG/pages/1181711/Marketplace+extensions+for+Azure+DevOps+release+process

You can also reach out to @alexandre-holzhey-sonarsource or @ivan-murenko-sonarsource they should be able to help as well :)

**Review by mickael-caro-sonarsource — APPROVED** [review]
LGTM. As said, please follow the release process as there's a need to track the release here : https://sonarsource.atlassian.net/projects/VSTS?selectedItem=com.atlassian.jira.jira-projects-plugin%3Arelease-page

Thanks !

**Comment by antonio-garcia-sonarsource** [comment]
> LGTM. As said, please follow the release process as there's a need to track the release here : https://sonarsource.atlassian.net/projects/VSTS?selectedItem=com.atlassian.jira.jira-projects-plugin%3Arelease-page
> 
> Thanks !

Hi again @mickael-caro-sonarsource I have been trying to figure this thing out but I might be missing something and I cannot understand it from the documentation. Do I need to manually create a Jira release as well? I might be missing permission to do that in that project.

**Pull request closed without merging**
